config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "flats#index"
  get "/condos/:id", to: "flats#show", as: :condo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"
require "json"

class FlatsController < ApplicationController
  def index 
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @condos = JSON.parse(URI.open(url).read)
  end

  def show
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @condos = JSON.parse(URI.open(url).read) 
    id = params[:id].to_i
    @condo = @condos.select do |condo|
      condo["id"] == id
    end
    @condo = @condo.first
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h1>Flats</h1>



  <% @condos.each do |condo| %>
    <div class="card">
     
      <img src="<%= condo['imageUrl'] %>" alt="" width="300px">
     
      <%= link_to condo["name"], condo_path(condo["id"]) %>
      <p>US$ <%= condo["price"] %></p>
    </div>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="container">
  
  <img src="<%= @condo['imageUrl'] %>" alt="<%= @condo['name'] %>" width="500px">
  <h1><%= @condo["name"] %></h1>
  <small><%= @condo["id"] %></small>
  <h2><%= @condo['price'] %> - <%= @condo["priceCurrency"] %></h2>
  <p><%= @condo["lat"] %></p>
  <p><%= @condo["lng"] %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>